package edu.codeschool.training.exceptions.homework11.quiz;

public class Question_1 {
    public static void main(String[] args) {
        //try {
        //    throw 10; // object must be throwable
        //}
        //catch (int e) {
        //    System.out.println("Got the exception " + e);
        //}
    }
}
